---
  baseUrl: http://localhost:8888
  appName: <%= packageName %>
  requiredHeaders:
    - fusion-api-key
    - authorization
    - content-type
  headerValues:
    fusion-api-key:
      - yourapikey
    content-type:
      - application/json
  db:
    bdName:
      host: localhost
      username: username
      password: password
