---
  requiredHeaders:
    - fusion-api-key
    - authorization
    - content-type
  headerValues:
    fusion-api-key:
      - key
    content-type:
      - application/json
  db:
    bdName:
      host: localhost
      username: username
      password: password
